- id: reuse-annotate
  name: Check and fix copyright headers with reuse annotate
  entry: ./scripts/run_reuse_annotate.sh
  language: system
  pass_filenames: false
  minimum_pre_commit_version: 3.2.0
