# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Synchronize the documented tool table with the lockfile catalog."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devcontainer.install import load_catalog_versions


TOOLS_DIR = Path(__file__).resolve().parent.parent
README_PATH = TOOLS_DIR / "README.md"
TABLE_START = "<!-- BEGIN GENERATED TOOL TABLE -->"
TABLE_END = "<!-- END GENERATED TOOL TABLE -->"

PURPOSES = {
    "actionlint": "Check GitHub Actions workflow files",
    "apm": "Manage APM packages",
    "bazelisk": "Run the Bazel version selected by a repository",
    "buildifier": "Format and lint Bazel files",
    "opencode": "Run the OpenCode CLI",
    "ruff": "Check and format Python code",
    "shellcheck": "Check shell scripts",
    "starpls": "Provide language-server support for Starlark",
    "uv": "Manage Python projects and packages",
    "uvx": "Run Python tools in isolated environments",
    "yamlfmt": "Format YAML files",
}


def _render_table(versions: dict[str, str]) -> str:
    undocumented = sorted(versions.keys() - PURPOSES.keys())
    stale_purposes = sorted(PURPOSES.keys() - versions.keys())
    if undocumented:
        raise SystemExit("Missing tool descriptions for: " + ", ".join(undocumented))
    if stale_purposes:
        raise SystemExit(
            "Descriptions exist without lockfile entries for: "
            + ", ".join(stale_purposes)
        )

    rows = [
        TABLE_START,
        "<!-- Generated by internal/sync_readme.py; do not edit manually. -->",
        "",
        "| Command | Version | Purpose |",
        "| --- | --- | --- |",
    ]
    rows.extend(
        f"| `{command}` | `{versions[command]}` | {PURPOSES[command]} |"
        for command in sorted(versions)
    )
    rows.extend(["", TABLE_END])
    return "\n".join(rows)


def _updated_readme(content: str, table: str) -> str:
    if content.count(TABLE_START) != 1 or content.count(TABLE_END) != 1:
        raise SystemExit(
            f"{README_PATH.name} must contain exactly one generated tool table"
        )

    start = content.index(TABLE_START)
    end = content.index(TABLE_END, start) + len(TABLE_END)
    return content[:start] + table + content[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize README tool versions with lockfiles.",
    )
    parser.parse_args(argv)

    current = README_PATH.read_text(encoding="utf-8")
    expected = _updated_readme(current, _render_table(load_catalog_versions()))

    if current == expected:
        return 0

    README_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
