# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Synchronize embedded version catalog in run-tool with lockfiles."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from devcontainer.install import load_catalog_versions

TOOLS_DIR = Path(__file__).resolve().parent.parent
RUN_TOOL_PATH = TOOLS_DIR / "run-tool"
RUN_TOOL_START = "# BEGIN GENERATED PINNED VERSIONS"
RUN_TOOL_END = "# END GENERATED PINNED VERSIONS"


def _render_pinned_versions(versions: dict[str, str]) -> str:
    lines = [
        RUN_TOOL_START,
        "# Generated by internal/sync_run_tool.py; do not edit manually.",
        "pinned_version() {",
        '    case "$1" in',
    ]
    for command in sorted(versions):
        lines.append(f"        {command}) printf '%s\\n' \"{versions[command]}\" ;;")
    lines.extend(
        [
            "        *) return 1 ;;",
            "    esac",
            "}",
            RUN_TOOL_END,
        ]
    )
    return "\n".join(lines)


def _updated_run_tool(content: str, block: str) -> str:
    if content.count(RUN_TOOL_START) != 1 or content.count(RUN_TOOL_END) != 1:
        raise SystemExit(
            f"{RUN_TOOL_PATH.name} must contain exactly one generated pinned versions block"
        )

    start = content.index(RUN_TOOL_START)
    end = content.index(RUN_TOOL_END, start) + len(RUN_TOOL_END)
    return content[:start] + block + content[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize run-tool embedded versions with lockfiles.",
    )
    parser.parse_args(argv)

    versions = load_catalog_versions()
    current = RUN_TOOL_PATH.read_text(encoding="utf-8")
    block = _render_pinned_versions(versions)
    expected = _updated_run_tool(current, block)

    if current == expected:
        return 0

    RUN_TOOL_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
